spring:
  application:
    name: productservice

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"