spring:
  application:
    name: eureka

server:
  port: 8888


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # kendini tan?tmaya ?al??mak
    fetch-registry: false # kendini tan?tan servis bilgilerini ?ekmeye ?al??mak
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/